### ==============================================================================
### SAP SuccessFactors Employee Central OData v2 Batch Ingestion Suite
### Module: 04-CPI-Integrations-and-OData
### Author: VPR11 | Vaibhav Paithankar
### Description: Atomic Multipart $batch Execution (PerPerson, EmpEmployment, EmpJob)
### ==============================================================================

@baseUrl = https://apisalesdemo4.successfactors.com/odata/v2
@apiUser = SF_CPI_INTEGRATION@CompanyProd
@apiPassword = {{SF_API_PASSWORD}}
@boundary = batch_sf_migration_boundary_001
@changesetBoundary = changeset_worker_e1001

### ------------------------------------------------------------------------------
### 1. Pre-Flight Health Check: Query API Metadata
### ------------------------------------------------------------------------------
# @name getMetadata
GET {{baseUrl}}/$metadata
Authorization: Basic {{apiUser}}:{{apiPassword}}
Accept: application/xml

### ------------------------------------------------------------------------------
### 2. Query Existing Legacy Worker Mapping Delta
### ------------------------------------------------------------------------------
# @name queryEmpJobDelta
GET {{baseUrl}}/EmpJob?$top=5&$select=userId,startDate,department,businessUnit,customString1,customString2&$filter=customString1 eq 'OU_PUNE_TECH'
Authorization: Basic {{apiUser}}:{{apiPassword}}
Accept: application/json

### ------------------------------------------------------------------------------
### 3. Multipart OData v2 $batch Ingestion (Atomic ChangeSet)
### ------------------------------------------------------------------------------
# @name executeBatchWorkerLoad
POST {{baseUrl}}/$batch
Authorization: Basic {{apiUser}}:{{apiPassword}}
Content-Type: multipart/mixed; boundary={{boundary}}

--{{boundary}}
Content-Type: multipart/mixed; boundary={{changesetBoundary}}

--{{changesetBoundary}}
Content-Type: application/http
Content-Transfer-Encoding: binary

POST PerPerson HTTP/1.1
Content-Type: application/json; charset=utf-8
Accept: application/json

{
  "personIdExternal": "EMP_GLOBAL_1001",
  "userId": "EMP_GLOBAL_1001",
  "perPerson": {
    "customString1": "MIGRATION_SOURCE_PEOPLESOFT"
  }
}

--{{changesetBoundary}}
Content-Type: application/http
Content-Transfer-Encoding: binary

POST EmpEmployment HTTP/1.1
Content-Type: application/json; charset=utf-8
Accept: application/json

{
  "personIdExternal": "EMP_GLOBAL_1001",
  "userId": "EMP_GLOBAL_1001",
  "startDate": "/Date(1787562000000+0000)/",
  "isContingentWorker": false,
  "originalStartDate": "/Date(1787562000000+0000)/"
}

--{{changesetBoundary}}
Content-Type: application/http
Content-Transfer-Encoding: binary

POST EmpJob HTTP/1.1
Content-Type: application/json; charset=utf-8
Accept: application/json

{
  "userId": "EMP_GLOBAL_1001",
  "startDate": "/Date(1787562000000+0000)/",
  "seqNumber": "1",
  "eventReason": "HIRNEW",
  "businessUnit": "TECH_CORP",
  "department": "ENG_SUPPORT_L2",
  "location": "LOC_PUN_01",
  "customString1": "OU_PUNE_TECH",
  "customString3": "ROLE_SUPPORT_ENG",
  "customString4": "FUNC_TECH_OPS",
  "customString5": "DOM_INFRA_SUPPORT",
  "customString6": false,
  "standardHours": 40.0,
  "payGrade": "GRADE_L2_IN"
}

--{{changesetBoundary}}--

--{{boundary}}--